### PR TITLE
Custom Bootstrap Website Draft 1

### PR DESCRIPTION
**Pull request by ACKAdeyemi**
Our website "Easy Cook Meals" is now ready to be pushed to Master branch.

Isabel worked on the About page.

I, Chris, worked on the Contact page.

We may add some extra things tomorrow morning - mainly styling e.g. colours and text content edits.

### CODE REVIEW

**Review by YannLL — COMMENTED** [review]
Super good code, everything is neat and easy to read 👍 .
The few changes needed are:
- Give contacts.html the same level of commenting / sectioning as your other pages.

- Organise / comments on your stylesheets

- Keep the readme concise? 
The code snippet includes a whole html page. If it's just a snippet, the sample html and CSS in lines 40-51 should suffice.

Five star work guys :)

**Comment by ACKAdeyemi** [comment]
Ready to go Yann

**Comment by ACKAdeyemi** [comment]
@isabelvalente hasn't pushed her changes to dev yet. You should see her changes appear here @YannLL

**Review by kenl94 — CHANGES_REQUESTED** [review]
Great work guys,

As Yann suggested, 
would like to see some comments as to what the styling is for.
Also on about.html, line 77 there is a random Z after the closing footer tag.

Once done, can merge to master

**Comment by isabelvalente** [comment]
Thank you for taking the time to check this Yann and Ken, really good feedback.

I added he comments to stylesheet first and pushed then I saw this message and removed the z from the about page and pushed again.


Isabel Valente
Trainee Consultant


[https://attachment.outlook.office.net/owa/IValente@spartaglobal.com/service.svc/s/GetFileAttachment?id=AAMkADg5ZWUzNGY1LWE4NWUtNDAwOC1iNWE3LWU1OTQxZDU3MDQwYQBGAAAAAADOsfod%2BTT%2FQI7Gty%2FcEaLRBwChAB%2FCLdVWT5MxWDSifxZmAAAAAAEMAAChAB%2FCLdVWT5MxWDSifxZmAAACbM6oAAABEgAQAI17c7cvE%2BZMv%2B79%2BT29rYc%3D&X-OWA-CANARY=_slM5cRnG06kiUCcJeKNQYAFzLiivNUY1kDfZ6Z1Z03490FAblIGZj_rTi3H-omF1bupETR7CI4.&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkJnRDU5blJpQnpmbk5BVGloOFJhZ1l5M3pyZyJ9.eyJ2ZXIiOiJFeGNoYW5nZS5DYWxsYmFjay5WMSIsImFwcGN0eHNlbmRlciI6Ik93YURvd25sb2FkQGZmMTVjNjdjLTI4NzAtNGU5Zi1hZGMxLTdkNjFkODU1YjY2NyIsImFwcGN0eCI6IntcIm1zZXhjaHByb3RcIjpcIm93YVwiLFwicHJpbWFyeXNpZFwiOlwiUy0xLTUtMjEtNTQ0MDQ1Mzk5LTE0MTIzMTM0NzEtMzc3NjM1MTYxNy0xMTE4NzQ3NlwiLFwicHVpZFwiOlwiMTE1MzgzNjI5Njg1NTYyNTEzNVwiLFwib2lkXCI6XCIwMjY5MThjYy0xYjMxLTRjYTQtOGNhNy1iOGEzMGExYmZhNGRcIixcInNjb3BlXCI6XCJPd2FEb3dubG9hZFwifSIsImlzcyI6IjAwMDAwMDAyLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMEBmZjE1YzY3Yy0yODcwLTRlOWYtYWRjMS03ZDYxZDg1NWI2NjciLCJhdWQiOiIwMDAwMDAwMi0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvYXR0YWNobWVudC5vdXRsb29rLm9mZmljZS5uZXRAZmYxNWM2N2MtMjg3MC00ZTlmLWFkYzEtN2Q2MWQ4NTViNjY3IiwiZXhwIjoxNTI2NjM2NzA2LCJuYmYiOjE1MjY2MzYxMDZ9.DUPLKIi-kUYvLNzpLCIgQYOMzikQx0VuH0rR1rDGOE0C0NFOXwKB8EI2aoa-8UuwrI4xOTaV_Z7sqtWEuwgUEE9ZiAbDmrfcnGtYCpcVYeCLYG-_paUJ_i-OK3mpGKYmZBr55EX-229ASYYic9kjoh4w3Ywdig3u6MNZftii21D2bKVnh_IbccdpEIApsdejpHAR9qAYpgt8rjXuXtP0n3ILKsvYDqOD-K83t76cMN9Rpx9T0m8M8EQJpdo7DacHs5taAzb1Zy8caEkuScrkRcLYNxKFx-5s4PNF8Sr6Lu8BBn6qBbLEZ0vVzYHu9riob6iMBN2ei0ZKlNpVlGgglw&owa=outlook.office365.com&isImagePreview=True]



UK Top 10 Graduate Employer

M: 07495494563
E: jmcgregor@spartaglobal.com<mailto:jmcgregor@spartaglobal.com>

Come and visit one of our tech training academies in Birmingham, London or Leeds and discover your future talent pipeline.

PS: Know someone who wants to build a new career in tech? Please put them in touch - we can help!

IMPORTANT NOTICE:
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the sender. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of Testing Circle Limited. Although Testing Circle Limited has taken every reasonable precaution to ensure that any e-mails have been checked for viruses, it is the responsibility of the recipient to ensure this e-mail and its attachments are virus free before opening. Testing Circle Limited accepts no liability for any damage caused by any virus transmitted by this email. Please note that Testing Circle Limited monitors e-mails sent or received. Further communication will signify your consent to this. Testing Circle Limited is a limited liability company registered in England and Wales under company no. 5597367.


On 24 May 2018, at 19:02, kenl94 <notifications@github.com<mailto:notifications@github.com>> wrote:


@kenl94 requested changes on this pull request.

Great work guys,

As Yann suggested,
would like to see some comments as to what the styling is for.
Also on about.html, line 77 there is a random Z after the closing footer tag.

One done, can merge to master

**Review by YannLL — APPROVED** [review]
All clean and good to go, well done guys :)

**Review by kenl94 — APPROVED** [review]

**Review by kenl94 — APPROVED** [review]
The changes have been made so good job guys!

**Pull request merged**
